language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  #- openjdk8
  - oraclejdk8

# Need to skip GPG signing of artifacts on install.
install: mvn install -DskipTests=true -Dgpg.skip=true

sudo: false
